
[env]
framework = arduino
extra_scripts =
    pre:version.py

[platformio]
build_cache_dir = .pio/build/cache

[env:robot_stm32h743vit6]
platform = https://github.com/platformio/platform-ststm32#v19.6.0
board = weact_mini_stm32h743vit6
lib_deps =
    adafruit-st7735-library
    GxEPD2
build_flags =
    -D BLE_DEVICE_NAME="\"robot_stm32h743vit6\""
    -D NET_HOSTNAME="\"robot_stm32h743vit6\""
    -D ROBOT_HAS_DISPLAY=1
    -D ROBOT_HAS_DISPLAY_GDEY0213Z98=1

[env:station_e213]
platform = https://github.com/pioarduino/platform-espressif32#55.03.38-1
board = heltec_vision_master_e213
lib_deps =
    heltec-eink-modules
build_flags =
    -D BLE_DEVICE_NAME="\"station_e213\""
    -D NET_HOSTNAME="\"station_e213\""
    -D ROBOT_HAS_DISPLAY=1
