
[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
lib_deps = 
	https://github.com/h2zero/NimBLE-Arduino#2.3.6
	https://github.com/jgromes/RadioLib#7.4.0
	https://github.com/tremaru/iarduino_Position_BMX055#1.2.4
extra_scripts = 
	pre:version.py
build_type = release
upload_protocol = esptool
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder

[env:robot_ota]
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D NET_HOSTNAME="\"robostar82\""
	-D OTA_PASSWORD="\"\""
	-D BLE_DEVICE_NAME="\"RoboStar82\""
	-D BLE_SECURITY_PASSKEY=
	-D ROBOT_ROLE_CHASSIS=1
	-D ROBOT_HAS_CONTROLLER_LORA=1
	-D ROBOT_HAS_TRANSCEIVER_SERIAL=1
	-D ROBOT_HAS_NAVIGATION_SERIAL=1
	-D ROBOT_HAS_MOTOR_MCPWM=1
	-D ROBOT_HAS_MOTOR_PWM=1
	-D ROBOT_HAS_SERVO_PWM=1
	-D ROBOT_HAS_IMU=1
board = esp32s3-n16r8
upload_protocol = espota
upload_port = robostar82.local
upload_flags = --auth=

[env:robot_usb]
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D NET_HOSTNAME="\"robostar82\""
	-D OTA_PASSWORD="\"\""
	-D BLE_DEVICE_NAME="\"RoboStar82\""
	-D BLE_SECURITY_PASSKEY=
	-D ROBOT_ROLE_CHASSIS=1
	-D ROBOT_HAS_CONTROLLER_LORA=1
	-D ROBOT_HAS_TRANSCEIVER_SERIAL=1
	-D ROBOT_HAS_NAVIGATION_SERIAL=1
	-D ROBOT_HAS_MOTOR_MCPWM=1
	-D ROBOT_HAS_MOTOR_PWM=1
	-D ROBOT_HAS_SERVO_PWM=1
	-D ROBOT_HAS_IMU=1
board = esp32s3-n16r8

[env:navigation_ota]
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D NET_HOSTNAME="\"robostar82n\""
	-D OTA_PASSWORD="\"N\""
	-D BLE_DEVICE_NAME="\"RoboStar82N\""
	-D BLE_SECURITY_PASSKEY=
	-D ROBOT_ROLE_NAVIGATION=1
	-D ROBOT_HAS_CONTROLLER_SERIAL=1
	-D ROBOT_HAS_NAVIGATION_SENDER=1
	-D ROBOT_HAS_MOTOR_ENCODER=1
	-D ROBOT_HAS_LIDAR=1
	-D ROBOT_HAS_IMU=0
board = esp32s3-n16r8
upload_protocol = espota
upload_port = robostar82n.local
upload_flags = --auth=N

[env:navigation_usb]
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D NET_HOSTNAME="\"robostar82n\""
	-D OTA_PASSWORD="\"N\""
	-D BLE_DEVICE_NAME="\"RoboStar82N\""
	-D BLE_SECURITY_PASSKEY=
	-D ROBOT_ROLE_NAVIGATION=1
	-D ROBOT_HAS_CONTROLLER_SERIAL=1
	-D ROBOT_HAS_NAVIGATION_SENDER=1
	-D ROBOT_HAS_MOTOR_ENCODER=1
	-D ROBOT_HAS_LIDAR=1
	-D ROBOT_HAS_IMU=0
board = esp32s3-n16r8

[env:transceiver_ota]
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D NET_HOSTNAME="\"robostar82t\""
	-D OTA_PASSWORD="\"T\""
	-D BLE_DEVICE_NAME="\"RoboStar82T\""
	-D BLE_SECURITY_PASSKEY=
	-D ROBOT_ROLE_TRANSCEIVER=1
	-D ROBOT_HAS_CONTROLLER_USB=1
	-D ROBOT_HAS_TRANSCEIVER_LORA=1
board = heltec_wireless_stick_lite_v3
board_build.variants_dir = variants
upload_protocol = espota
upload_port = robostar82t.local
upload_flags = --auth=T

[env:transceiver_usb]
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D NET_HOSTNAME="\"robostar82t\""
	-D OTA_PASSWORD="\"T\""
	-D BLE_DEVICE_NAME="\"RoboStar82T\""
	-D BLE_SECURITY_PASSKEY=
	-D ROBOT_ROLE_TRANSCEIVER=1
	-D ROBOT_HAS_CONTROLLER_USB=1
	-D ROBOT_HAS_TRANSCEIVER_LORA=1
board = heltec_wireless_stick_lite_v3
board_build.variants_dir = variants
