
[env]
framework = arduino
platform = espressif32

[env:esp32s3-n16r8]
lib_deps = 
	tremaru/iarduino_I2C_Motor@^1.1.6
	tremaru/iarduino_Position_BMX055@^1.2.4
build_flags = 
	-DBLE_DEVICE_NAME="\"RoboStar82\""
	-DROBOT_HAS_LED=0
	-DROBOT_HAS_BMX=0
	-DROBOT_HAS_LIDAR=0
	-DROBOT_HAS_SERVO=0
	-DROBOT_HAS_MOTOR_I2C=1
	-DROBOT_HAS_MOTOR_PWM=0
	-DROBOT_HAS_CONTROLLER_PS3=0
	-DROBOT_HAS_CONTROLLER_BLE=1
	-DROBOT_HAS_BATTERY=1
board = esp32s3-n16r8
upload_port = /dev/cu.wchusbserial*
monitor_port = /dev/cu.wchusbserial*
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

[env:esp32s3-n16r8-debug]
lib_deps = 
	tremaru/iarduino_I2C_Motor@^1.1.6
	tremaru/iarduino_Position_BMX055@^1.2.4
build_flags = 
	-DBLE_DEVICE_NAME="\"RoboStar82\""
	-DROBOT_HAS_LED=0
	-DROBOT_HAS_BMX=0
	-DROBOT_HAS_LIDAR=0
	-DROBOT_HAS_SERVO=0
	-DROBOT_HAS_MOTOR_I2C=1
	-DROBOT_HAS_MOTOR_PWM=0
	-DROBOT_HAS_CONTROLLER_PS3=0
	-DROBOT_HAS_CONTROLLER_BLE=1
	-DROBOT_HAS_BATTERY=1
board = esp32s3-n16r8
upload_port = /dev/cu.wchusbserial*
monitor_port = /dev/cu.wchusbserial*
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder
build_type = debug

[env:esp32-wroom-32e]
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.1
build_flags = 
	-DBLE_DEVICE_NAME="\"RoboStar82\""
	-DROBOT_HAS_LED=1
	-DROBOT_HAS_BMX=0
	-DROBOT_HAS_LIDAR=0
	-DROBOT_HAS_SERVO=0
	-DROBOT_HAS_MOTOR_I2C=0
	-DROBOT_HAS_MOTOR_PWM=1
	-DROBOT_HAS_CONTROLLER_PS3=0
	-DROBOT_HAS_CONTROLLER_BLE=1
	-DROBOT_HAS_BATTERY=0
board = esp32dev
upload_port = /dev/cu.wchusbserial*
monitor_port = /dev/cu.wchusbserial*
upload_speed = 921600
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

[env:esp32-wroom-32e-debug]
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.1
build_flags = 
	-DBLE_DEVICE_NAME="\"RoboStar82\""
	-DROBOT_HAS_LED=1
	-DROBOT_HAS_BMX=0
	-DROBOT_HAS_LIDAR=0
	-DROBOT_HAS_SERVO=0
	-DROBOT_HAS_MOTOR_I2C=0
	-DROBOT_HAS_MOTOR_PWM=1
	-DROBOT_HAS_CONTROLLER_PS3=0
	-DROBOT_HAS_CONTROLLER_BLE=1
	-DROBOT_HAS_BATTERY=0
board = esp32dev
upload_port = /dev/cu.wchusbserial*
monitor_port = /dev/cu.wchusbserial*
upload_speed = 921600
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder
build_type = debug

[env:esp32-wroom-32e-2]
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.1
build_flags = 
	-DBLE_DEVICE_NAME="\"RoboStar82A\""
	-DROBOT_HAS_LED=1
	-DROBOT_HAS_BMX=0
	-DROBOT_HAS_LIDAR=0
	-DROBOT_HAS_SERVO=1
	-DROBOT_HAS_MOTOR_I2C=0
	-DROBOT_HAS_MOTOR_PWM=0
	-DROBOT_HAS_CONTROLLER_PS3=0
	-DROBOT_HAS_CONTROLLER_BLE=1
	-DROBOT_HAS_BATTERY=0
board = esp32dev
upload_port = /dev/cu.wchusbserial*
monitor_port = /dev/cu.wchusbserial*
upload_speed = 921600
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

[env:esp32-wroom-32e-2-debug]
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.1
build_flags = 
	-DBLE_DEVICE_NAME="\"RoboStar82A\""
	-DROBOT_HAS_LED=1
	-DROBOT_HAS_BMX=0
	-DROBOT_HAS_LIDAR=0
	-DROBOT_HAS_SERVO=1
	-DROBOT_HAS_MOTOR_I2C=0
	-DROBOT_HAS_MOTOR_PWM=0
	-DROBOT_HAS_CONTROLLER_PS3=0
	-DROBOT_HAS_CONTROLLER_BLE=1
	-DROBOT_HAS_BATTERY=0
board = esp32dev
upload_port = /dev/cu.wchusbserial*
monitor_port = /dev/cu.wchusbserial*
upload_speed = 921600
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder
build_type = debug
