
#pragma once

#ifdef ARDUINO_GENERIC_ESP32_S3_N16R8

#define ROBOT_HAS_BLE
#define ROBOT_HAS_OTA
#define ROBOT_HAS_OTA_GDB
#define ROBOT_HAS_OTA_HTTP
#define ROBOT_HAS_OTA_UART
#define ROBOT_HAS_LED
#define ROBOT_HAS_PROXY
#define ROBOT_HAS_PROXY_HTTP
#define ROBOT_HAS_PROXY_UART
#define ROBOT_HAS_SETTINGS
#define ROBOT_HAS_READER
#define ROBOT_HAS_WRITER

#include <soc/gpio_num.h>

#define ROBOT_OTA_GDB_PORT 3333
#define ROBOT_OTA_GDB_SWCLK_PIN GPIO_NUM_4
#define ROBOT_OTA_GDB_SWDIO_PIN GPIO_NUM_5
#define ROBOT_OTA_UART_PORT 2323
#define ROBOT_PROXY_TX_PIN 1
#define ROBOT_PROXY_RX_PIN 2

#define ProxySerial Serial2

#endif
