
#pragma once

#ifdef ARDUINO_GENERIC_ESP32_S3_N16R8

#define ROBOT_HAS_BLE
#define ROBOT_HAS_OTA
#define ROBOT_HAS_OTA_GDB
#define ROBOT_HAS_OTA_HTTP
#define ROBOT_HAS_OTA_UART
#define ROBOT_HAS_LED
// #define ROBOT_HAS_LORA
#define ROBOT_HAS_PROXY
#define ROBOT_HAS_PROXY_HTTP
#define ROBOT_HAS_PROXY_UART
#define ROBOT_HAS_SETTINGS
#define ROBOT_HAS_READER
#define ROBOT_HAS_WRITER

#define OTA_GDB_PORT 3333
#define OTA_GDB_SWCLK_PIN 4
#define OTA_GDB_SWDIO_PIN 5
#define OTA_GDB_NRST_PIN 6
#define OTA_UART_PORT 2323

#define LORA_NSS_PIN 10
#define LORA_SCK_PIN 12
#define LORA_MISO_PIN 13
#define LORA_MOSI_PIN 11
#define LORA_NRST_PIN 3
#define LORA_BUSY_PIN 46
#define LORA_DIO1_PIN 14

#define PROXY_TX_PIN 1
#define PROXY_RX_PIN 2

#define ProxySerial Serial2

#endif
