
#pragma once

#ifdef ARDUINO_HELTEC_VISION_MASTER_E213

#define ROBOT_HAS_BLE
#define ROBOT_HAS_OTA
#define ROBOT_HAS_OTA_HTTP
#define ROBOT_HAS_OTA_UART
#define ROBOT_HAS_LED
// #define ROBOT_HAS_USB
#define ROBOT_HAS_LORA
#define ROBOT_HAS_LORA_FSK
#define ROBOT_HAS_PROXY_LORA
#define ROBOT_HAS_DISPLAY
#define ROBOT_HAS_DISPLAY_E0213A367
#define ROBOT_HAS_CONTROLLER
#define ROBOT_HAS_CONTROLLER_BLE
// #define ROBOT_HAS_CONTROLLER_USB
#define ROBOT_HAS_SETTINGS
#define ROBOT_HAS_WRITER

#define OTA_GDB_PORT 3333
#define OTA_GDB_SWCLK_PIN -1
#define OTA_GDB_SWDIO_PIN -1
#define OTA_UART_PORT 2323

#define LORA_NSS_PIN 8
#define LORA_SCK_PIN 9
#define LORA_MISO_PIN 11
#define LORA_MOSI_PIN 10
#define LORA_NRST_PIN 12
#define LORA_BUSY_PIN 13
#define LORA_DIO1_PIN 14

#endif
