
#pragma once

#ifdef ARDUINO_HELTEC_VISION_MASTER_E213

#define ROBOT_HAS_BLE
#define ROBOT_HAS_BLE_CONTROLLER
#define ROBOT_HAS_OTA
#define ROBOT_HAS_OTA_GDB
#define ROBOT_HAS_OTA_HTTP
#define ROBOT_HAS_OTA_UART
#define ROBOT_HAS_LED
#define ROBOT_HAS_USB
#define ROBOT_HAS_SCRIPT
#define ROBOT_HAS_DISPLAY
#define ROBOT_HAS_DISPLAY_E0213A367
#define ROBOT_HAS_CONTROLLER
#define ROBOT_HAS_SETTINGS
#define ROBOT_HAS_READER
#define ROBOT_HAS_WRITER

#include <soc/gpio_num.h>

#define ROBOT_OTA_GDB_PORT 3333
#define ROBOT_OTA_GDB_SWCLK_PIN GPIO_NUM_MAX
#define ROBOT_OTA_GDB_SWDIO_PIN GPIO_NUM_MAX
#define ROBOT_OTA_UART_PORT 2323

#endif
